; ===========================================================================================================================
; Constants for positional elements in 3Shape
; ===========================================================================================================================

global 3shapeButtons := {"":""
, "allViewX":"1902"
, "topViewY":"286"
, "bottomViewY":"253"
, "rightViewY":"215"
, "leftViewY":"177"
, "frontViewY":"106"
, "backViewY":"140"
, "transparencyX":"800"
, "transparencyY":"800"
, "":""
, "artifactX":"120"
, "artifacty":"173"
, "planeCutX":"165"
, "planeCutY":"175"
, "splineCutX":"205"
, "splineCutY":"175"
, "splineSmoothX":"195"
, "splineSmoothY":"300"
, "waxKnifeX":"35"
, "waxKnifeY":"175"
, "nextButtonX":"190"
, "nextButtonY":"30"
, "":""
, "newPatientModelX":"78"
, "newPatientModelY":"46"
, "":""}

global 3shapeFields := {"":""
, "advSearchFirst":"TEdit10"
, "advSearchLast":"TEdit9"
, "advSearchClinic":"Edit1"
, "advSearchScript2019":"TEdit16"
, "advSearchGo":"TButton2"
, "newPatientExt":"TEdit4"
, "newPatientFirst":"TEdit10"
, "newPatientLast":"TEdit9"
, "newPatientClinic":"Edit1"
, "newModelScript":"TEdit5"
, "":""}